{% set name = "freesas" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/freesas-{{ version }}.tar.gz
  sha256: 4b919ddea2d732a805a94b99482e68b3184f6348cfae52dec3c1fd0267dbcabd

build:
  ignore_run_exports_from:
  # cxx standard library is unused
    - {{ compiler('cxx') }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - free_gpa = freesas.app.auto_gpa:main
    - free_guinier = freesas.app.auto_guinier:main
    - free_rg = freesas.app.autorg:main
    - cormapy = freesas.app.cormap:main
    - supycomb = freesas.app.supycomb:main
    - free_bift = freesas.app.bift:main
    - freesas = freesas.app.plot_sas:main
    - extract_ascii = freesas.app.extract_ascii:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - wheel
    - setuptools <60.0.0
    - cython
    - numpy
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - six
    - scipy
    - matplotlib-base
    - pyfai-base

test:
  imports:
    - freesas
  commands:
    - free_gpa --help
    - free_guinier --help
    - free_rg --help
    - cormapy --help
    - supycomb --help
    - free_bift --help
    - freesas --help
    - extract_ascii --help
    - freesas --version

about:
  home: http://www.silx.org/
  summary: Free tools to analyze Small angle scattering data
  dev_url: https://github.com/kif/freesas
  doc_url: https://freesas.readthedocs.io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beenje
