{% set name = "freesas" %}
{% set version = "2024.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/freesas-{{ version }}.tar.gz
  sha256: 894574396cbe4c695031d06a7379e39db12dc903dd4aac6e629871284ef1da0a

build:
  ignore_run_exports_from:
  # cxx standard library is unused
    - {{ compiler('cxx') }}
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - free_gpa = freesas.app.auto_gpa:main
    - free_guinier = freesas.app.auto_guinier:main
    - free_rg = freesas.app.autorg:main
    - cormapy = freesas.app.cormap:main
    - supycomb = freesas.app.supycomb:main
    - free_bift = freesas.app.bift:main
    - freesas = freesas.app.plot_sas:main
    - extract_ascii = freesas.app.extract_ascii:main

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - ninja
  host:
    - python
    - pip
    - wheel
    - meson-python >=0.11
    - meson >=0.64
    - cython
    - numpy
    - pyproject-metadata >=0.5.0
    - tomli >=1.0.0
    - scipy
    - silx
  run:
    - python
    - scipy
    - matplotlib-base
    - pyfai-base
    - silx

test:
  imports:
    - freesas
  commands:
    - free_gpa --help
    - free_guinier --help
    - free_rg --help
    - cormapy --help
    - supycomb --help
    - free_bift --help
    - freesas --help
    - extract_ascii --help
    - freesas --version

about:
  home: http://www.silx.org/
  summary: Free tools to analyze Small angle scattering data
  dev_url: https://github.com/silx-kit/freesas
  doc_url: https://freesas.readthedocs.io
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beenje
